
import { UserRole, Permissions } from './types';

// Define default permissions per role
const defaultPermissions: Record<UserRole, Permissions> = {
  system_admin: {
    // System admin has all permissions
    canManageAllOrganizations: true,
    canConfigureGlobalIntegrations: true,
    canSetSecurityPolicies: true,
    canViewSystemWideAnalytics: true,
    canAccessSystemSettings: true,
    canManageTeamMembers: true,
    canControlBilling: true,
    canAddHotels: true,
    canEditHotels: true,
    canApproveHotels: true,
    canSubmitHotels: true,
    canSetPreferredVendors: true,
    canImportExportHotels: true,
    canAccessAllCompanyQuotes: true,
    canAssignInquiries: true,
    canGenerateQuotes: true,
    canModifyQuotes: true,
    canManageAgents: true,
    canViewTeamMetrics: true,
    canViewCompanyReports: true,
    canCommunicateWithClients: true,
  },
  
  org_owner: {
    canManageAllOrganizations: false,
    canConfigureGlobalIntegrations: false,
    canSetSecurityPolicies: false,
    canViewSystemWideAnalytics: false,
    canAccessSystemSettings: false,
    canManageTeamMembers: true,
    canControlBilling: true,
    canAddHotels: true,
    canEditHotels: true,
    canApproveHotels: true,
    canSubmitHotels: true,
    canSetPreferredVendors: true,
    canImportExportHotels: true,
    canAccessAllCompanyQuotes: true,
    canAssignInquiries: true,
    canGenerateQuotes: true,
    canModifyQuotes: true,
    canManageAgents: true,
    canViewTeamMetrics: true,
    canViewCompanyReports: true,
    canCommunicateWithClients: true,
  },
  
  tour_operator: {
    canManageAllOrganizations: false,
    canConfigureGlobalIntegrations: false,
    canSetSecurityPolicies: false,
    canViewSystemWideAnalytics: false,
    canAccessSystemSettings: false,
    canManageTeamMembers: false,
    canControlBilling: false,
    canAddHotels: true,
    canEditHotels: true,
    canApproveHotels: true,
    canSubmitHotels: true,
    canSetPreferredVendors: true,
    canImportExportHotels: false,
    canAccessAllCompanyQuotes: false,
    canAssignInquiries: true,
    canGenerateQuotes: true,
    canModifyQuotes: true,
    canManageAgents: true, // Tour operators can manage agents
    canViewTeamMetrics: true,
    canViewCompanyReports: false,
    canCommunicateWithClients: true,
  },
  
  agent: {
    canManageAllOrganizations: false,
    canConfigureGlobalIntegrations: false,
    canSetSecurityPolicies: false,
    canViewSystemWideAnalytics: false,
    canAccessSystemSettings: false,
    canManageTeamMembers: false,
    canControlBilling: false,
    canAddHotels: true,
    canEditHotels: false,
    canApproveHotels: false,
    canSubmitHotels: true,
    canSetPreferredVendors: false,
    canImportExportHotels: false,
    canAccessAllCompanyQuotes: false,
    canAssignInquiries: false,
    canGenerateQuotes: true,
    canModifyQuotes: true,
    canManageAgents: false,
    canViewTeamMetrics: false,
    canViewCompanyReports: false,
    canCommunicateWithClients: true,
  },
  
  client: {
    canManageAllOrganizations: false,
    canConfigureGlobalIntegrations: false,
    canSetSecurityPolicies: false,
    canViewSystemWideAnalytics: false,
    canAccessSystemSettings: false,
    canManageTeamMembers: false,
    canControlBilling: false,
    canAddHotels: false,
    canEditHotels: false,
    canApproveHotels: false,
    canSubmitHotels: false,
    canSetPreferredVendors: false,
    canImportExportHotels: false,
    canAccessAllCompanyQuotes: false,
    canAssignInquiries: false,
    canGenerateQuotes: false,
    canModifyQuotes: false,
    canManageAgents: false,
    canViewTeamMetrics: false,
    canViewCompanyReports: false,
    canCommunicateWithClients: true,
  }
};

export default defaultPermissions;
