// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtwgyakeufqghnnmeovh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0d2d5YWtldWZxZ2hubm1lb3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzAwNjgsImV4cCI6MjA2NTU0NjA2OH0.ygMAMIEPsUA-Kx0BXXWxhQTXGL2zLTYD1dP3AVIE2gI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);