// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mislxibukncnmvwhsiml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pc2x4aWJ1a25jbm12d2hzaW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODQ0NTYsImV4cCI6MjA2MzE2MDQ1Nn0.K7M9I0zJfbYhXZtHYqJVr3G8AzuLl1xOBpF0zjxZxro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);